### ISSUE TITLE
rsync failing when using gitlab-ci

### ISSUE THREAD

**Issue by ELepolt** [michaljach/ember-cli-deploy-scp#33]
`ember deploy production` works fine locally, and I've made sure that the rsync command is the same on both my local and gitlab's variables

Relevant `ember-cli-deploy-scp` code on gitlab pipeline

```
|    - Beginning upload to rails@159.203.127.88:/var/www/html/
|    - rsync -rtvu --rsh="ssh -p 22" tmp/deploy-dist/. rails@ipaddress:/var/www/html/20190723T1333
|    - Error: rsync exited with code 12
```

I know that that is the 'exited with code 12' error that is linked to on the readme, but I am positive that the path exists, especially since it's working locally and I can run the rsync command manually.

`.gitlab-ci.yml`

```
image: node:latest

stages:
  - deploy

production:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - 'which rsync || ( apt-get update -y && apt-get install rsync -y )'
    # Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)
    # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "SSH_USERNAME="$SSH_USERNAME >> .env
    - echo "SSH_HOST="$SSH_HOST >> .env
    - echo "SSH_PATH="$SSH_PATH >> .env
    - echo "SSH_DIR="$SSH_DIR >> .env
  script:
    - npm install
    - ember deploy production -v
  only:
    - master
```

I follow [this doc](https://docs.gitlab.com/ee/ci/ssh_keys/) regarding getting SSH keys properly set up for the project including the server's public key as a [deploy key](https://docs.gitlab.com/ee/ssh/README.html#deploy-keys).

Been going at this for a day or so now, any ideas would be extremely helpful.
